### ISSUE TITLE
Stuck on retrying requests status code 409

### ISSUE THREAD

**Issue by soapy75** [hackermondev/replit-exporter#1]
I just wanted to start off by saying this tool is amazing, Ive been very upset with the changes made by replit and the tool is being a great help in migrating to another platform. 

It has gone through alot of my replits, but it is currently stuck on retrying requests to some of my files, recieving error code 409. there has been no updates for around 5minutes. If i restart, will it duplicate all my files?

Thanks again.

**Comment by soapy75** [comment]
update: its spamming that for every new file it finds, it is being ratelimited, and retrying. I will wait for it to mabye sort itself out.

**Comment by hackermondev** [comment]
> I just wanted to start off by saying this tool is amazing, Ive been very upset with the changes made by replit and the tool is being a great help in migrating to another platform.


Thanks :)

> It has gone through alot of my replits, but it is currently stuck on retrying requests to some of my files, recieving error code 409. there has been no updates for around 5minutes. If i restart, will it duplicate all my files?

Make sure you're on the latest version (replit-export@1.0.11), fixed some issues there. I'm still not sure why it randomly 409s for some repls, but I made it just incrementally retry it (and it usually goes back to normally after 3-4 tries).  You might see logs about it retrying requests when it does this, it doesn't log when requests succeed though so you'll know its back to normal when when it stops retrying requests.

And, no it shouldn't duplicate. I intentionally implemented a [save file](https://github.com/hackermondev/replit-exporter?tab=readme-ov-file#command-options) (`--load`) functionality which it automatically uses even if not configured. You can stop it at anytime and if you restart from the same directory it should automatically resume from where it stopped.

> update: its spamming that for every new file it finds, it is being ratelimited, and retrying. I will wait for it to mabye sort itself out.

Yeah, the rate limit is really annoying. It's like ~45 repls every 30 minutes(?) still looking for ways around it. That's why its highly recommend to just leave it in the background while it works.

**Comment by soapy75** [comment]
> > I just wanted to start off by saying this tool is amazing, Ive been very upset with the changes made by replit and the tool is being a great help in migrating to another platform.
> 
> 
> Thanks :)
> 
> > It has gone through alot of my replits, but it is currently stuck on retrying requests to some of my files, recieving error code 409. there has been no updates for around 5minutes. If i restart, will it duplicate all my files?
> 
> Make sure you're on the latest version (replit-export@1.0.11), fixed some issues there. I'm still not sure why it randomly 409s for some repls, but I made it just incrementally retry it (and it usually goes back to normally after 3-4 tries).  You might see logs about it retrying requests when it does this, it doesn't log when requests succeed though so you'll know its back to normal when when it stops retrying requests.
> 
> And, no it shouldn't duplicate. I intentionally implemented a [save file](https://github.com/hackermondev/replit-exporter?tab=readme-ov-file#command-options) (`--load`) functionality which it automatically uses even if not configured. You can stop it at anytime and if you restart from the same directory it should automatically resume from where it stopped.
> 
> > update: its spamming that for every new file it finds, it is being ratelimited, and retrying. I will wait for it to mabye sort itself out.
> 
> Yeah, the rate limit is really annoying. It's like ~45 repls every 30 minutes(?) still looking for ways around it. That's why its highly recommend to just leave it in the background while it works.
> 

Thanks for the reply, the save feature is really convenient, I let it run for longer but still encountered some errors after a while of running it, most of the files are downloaded, I'm going to leave it till next morning to give it some time to cool off.

There was an error that would abort the program where it was denied permission or something to one of the folders that was downloaded, but was easily fixed by deleting the said folder and re running the program.
